### ISSUE TITLE
Evaluation Difference to DCP

### ISSUE THREAD

**Issue by fa9r** [yewzijian/RPMNet#12]
Hi yewzijian,

I noticed that your evaluation results are totally different from the ones reported by DCP paper (https://arxiv.org/pdf/1905.03304.pdf).

In particular, DCP reports that it is much better than FGR and PointNetLK, whereas in your comparison those methods achieve up to 100x lower errors and outperform DCP. So I was wondering if you use the same evaluation setup as DCP or if there is some important difference that I missed?

Best regards,
Felix

**Comment by yewzijian** [comment]
Hi Felix,

Yes you are right that the results are different. I reran all baselines
(including DCP) and listed my numbers. The evaluation is likely to be the
same as I obtained similar accuracies for DCP to what is reported in their
paper. You can also verify that my evaluation code produces the same result
as DCP’s when given the same input.

I believe the differences come from the parameter settings of
pointnetLK/FGR/ICP. FGR. They do require slight tuning to achieve the
numbers I reported, and I’ll be glad to pass you my parameters if you need.

Lastly, do note that only the clean dataset setting is supposed to be
comparable. The noisy setting is different from DCP due to differences in
the data preparation.


Zi Jian

**Comment by fa9r** [comment]
Thanks for the fast response :)
