### ISSUE TITLE
A question about the isotropic metric

### ISSUE THREAD

**Issue by qsisi** [yewzijian/RPMNet#22]
Hello!

My question is, is the isotropic metrics defined originally by you or you get from somewhere else? It would be great if you can explain how to formulate this metric in mathmatics.

Thanks so much for your help!

**Comment by yewzijian** [comment]
Those are standard metrics for comparing two rigid transformations (and actually more common than the metrics in DCP). For example, the same metrics are used in [here](https://arxiv.org/pdf/2001.05119.pdf) (see Eq 18).

The term "isotopic" is not typical though; I used it to differentiate from the metrics in DCP since those are sensitive to the direction.


Regards,
Zi Jian

**Comment by qsisi** [comment]
Thanks!
